### ISSUE TITLE
about unknown source

### ISSUE THREAD

**Issue by hilk** [armhold/polygen#2]
hi, i am new here if i am making something wrong sorry. when i try  
`polygen -source images/mona_lisa.jpg -poly 20`
 i get this error 

> /usr/games/polygen: unknown option '-source'.

**Comment by armhold** [comment]
Hi hilk,

Look at the output error message and you will see that it's invoking the wrong program ("/usr/games/polygen").

You can invoke it directly with:

    $GOPATH/bin/polygen

The better solution is probably to add $GOPATH/bin to your PATH, a per the golang documentation.
